# For full fine-tuning, LoRA training, and evaluation

FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    git wget curl vim \
    python3 python3-pip python3-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    apt-get update && \
    apt-get install -y git-lfs && \
    git lfs install

ENV CONDA_DIR=/opt/conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    bash miniconda.sh -b -p $CONDA_DIR && \
    rm miniconda.sh

ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

RUN conda create -n emosum python=3.8

SHELL ["conda", "run", "-n", "emosum", "/bin/bash", "-c"]

WORKDIR /workspace
COPY requirements.txt /workspace/requirements.txt

RUN python -m pip install -U pip --user
RUN pip install --upgrade pip && pip install -r requirements.txt

RUN python - <<EOF
import nltk
nltk.download("punkt")
EOF

CMD ["/bin/bash"]